// Place your copyright here

// File generated by code metagenerator from
// - file: 	    ./test/_generated/comment.h
// - generator: ../C:/Users/wgan/Desktop/WGan/PROGRAMOWANIE/meth/source/MAIN.py
// - template:  ./templates/simple_data_objects/object_type.h.template

#include <string>

// -vvv additional includes and declarations could be written here

	// code written here will be preserved during future
	// generation of this file

// -^^^ end of manualy entered code

namespace Data
{
    class Comment
	{
		public:
			Comment(const std::string& value = ) explicit
			: 	m_Comment { value }
			{   }

			Comment(std::string&& value)
			: 	m_Comment { value }
			{   }

			std::string getComment() const
			{
				return m_Comment;
			}

			void setComment(const std::string& newValue)
			{
				m_Comment = newValue;
			}

			void setComment(std::string&& newValue)
			{
				m_Comment = newValue;
			}

			// -vvv additional methods could be written here

				// code written here will be preserved during future
				// generation of this file

			// -^^^ end of manualy entered code

		private:
			std::string m_Comment;
	};
}