// Place your copyright here

// File generated by code metagenerator from
// - file: 	    ../meth/test/_generated/story_points.h
// - generator: ../meth/source/MAIN.py
// - template:  ../meth/templates/simple_type.h.template

namespace Data
{
    class StoryPoints
	{
		public:
			StoryPoints(uint16_t value = 0) explicit
			: 	m_StoryPoints { value }
			{   }

			uint16_t getStoryPoints() const
			{
				return m_StoryPoints;
			}

			void setStoryPoints(uint16_t newValue)
			{
				m_StoryPoints = newValue;
			}

			// -vvv additional methods could be written here

				// code written here will be preserved during future
				// generation of this file

			// -^^^ end of manualy entered code

		private:
			uint16_t m_StoryPoints;
	};
}