// Place your copyright here

// File generated by code metagenerator from
// - file: 	    ./test/_generated/type.cpp
// - generator: ../C:/Users/wgan/Desktop/WGan/PROGRAMOWANIE/meth/source/simple_data_objects.py
// - template:  ./templates/simple_data_objects/enum_type.cpp.template

#include "type.h"

// -vvv additional includes and declarations could be written here

	// code written here will be preserved during future
	// generation of this file

// -^^^ end of manualy entered code

namespace Data
{
	const char* const Type::names[] =
    {
		"Task",   "Index",  "Sprint"
    }

	Type Type::from_string(const std::string& text)
	{
		switch( text.size() )
		{
		case 4:
		    return Task;
		case 5:
		    return Index;
		default:
		    return Sprint;
		};
	}

	// -vvv additional methods could be written here

		// code written here will be preserved during future
		// generation of this file

	// -^^^ end of manualy entered code
}