// --------------------------------------------------------------------------------------
// File generated by metamorph meth code generator. File may be modified only inside 
// specially marked code blocks. Only such code can survive during subsequent generation 
// of the file. All other modification can be overwritten when generator is started.
// --------------------------------------------------------------------------------------
// This file is stored at:      .../development/test-of-generated-code/common_text_mesage.h
// and it is generated by:      .../test.py[111]
// based on pattern file:       .../patterns/string.h.body.pattern
// wrapped by pattern:          .../patterns/source.main.pattern
// (where '...' is solution root path)
// --------------------------------------------------------------------------------------

#pragma once

#include <cstdint>
#include <string>
#include <iostream>

#include "serialization_binary_serialization.h"

// -vvv YOU CAN PUT ADDITIONAL INCLUDES BELOW

// -^^^ END OF USER DEFINED INCLUDES

namespace Common
{
  class TextMesage
  {
    public:
      // type traits
      static constexpr const char* class_name = { "Common::TextMesage" };
      static constexpr bool is_compareable = { true };
      static constexpr bool is_ordered = { true };
      static constexpr uint16_t max_length = { 4000 };
  
      constexpr TextMesage() noexcept
        : m_text_mesage("No comments.")
      {  }
  
      constexpr explicit TextMesage( const std::string& text_mesage ) noexcept
        : m_text_mesage(text_mesage)
      {  }
  
      TextMesage(const TextMesage& text_mesage) noexcept = default;
      TextMesage(TextMesage&& text_mesage) noexcept = default;
      TextMesage& operator=(const TextMesage& text_mesage) noexcept = default;
      TextMesage& operator=(TextMesage&& text_mesage) noexcept = default;
  
  
  
  
  
  
    private:
      std::string m_text_mesage;
  
      // -vvv YOU CAN PUT ADDITIONAL CLASS ELEMENTS BELOW
  
      // -^^^ END OF USER DEFINED CLASS ELEMENTS
  };
} // end Common
