// --------------------------------------------------------------------------------------
// File generated by metamorph meth code generator. File may be modified only inside 
// specially marked code blocks. Only such code can survive during subsequent generation 
// of the file. All other modification can be overwritten when generator is started.
// --------------------------------------------------------------------------------------
// This file is stored at:      .../development/test-of-generated-code/common_severity.h
// and it is generated by:      .../test.py[96]
// based on pattern file:       .../patterns/enum.h.body.pattern
// wrapped by pattern:          .../patterns/common.main.pattern
// (where '...' is solution root path)
// --------------------------------------------------------------------------------------

#pragma once

#include <cstdint>
#include <string>
#include <iostream>

#include "serialization_binary_serialization.h"

// vvv--- YOU CAN PUT ADDITIONAL INCLUDES BELOW

// ^^^--- END OF USER DEFINED INCLUDES

namespace Common
{
  class Severity
  {
    public:
      // type traits
      static constexpr const char* class_name = { "Common::Severity" };
      static constexpr bool is_compareable = { true };
      static constexpr bool is_ordered = { true };
      static constexpr bool size_in_bytes = { 1 };
  
      // internal value type
      enum eSeverity : uint8_t 
      {
        E_DATA,
        E_MEMO,
        E_NOTICE,
        E_INFO,
        E_TRACE,
        E_DEBUG,
        E_LOG,
        E_WARNING,
        E_PROBLEM,
        E_ERROR,
        E_FATAL,
        E_DISASTER,
        E_ARMAGEDON
      };
  
      static constexpr eSeverity first_value = { E_DATA };
      static constexpr eSeverity last_value = { E_ARMAGEDON } ;
  
      Severity() noexcept
      : m_severity(E_INFO)
      {  }
      
      constexpr explicit Severity(eSeverity severity) noexcept
      : m_severity(severity)
      {  }
      
      Severity(const Severity& severity) noexcept = default;
      Severity(Severity&& severity) noexcept = default;
      Severity& operator=(const Severity& severity) noexcept = default;
      Severity& operator=(Severity&& severity) noexcept = default;
  
      eSeverity getSeverityAsEnum() const noexcept { return m_severity; }
      uint8_t getSeverityAsInt() const noexcept { return m_severity; }
  
      const Severity& getSeverity() const noexcept { return *this; }
      
      void setSeverity(const Severity& severity) { *this = severity; }
      void setSeverity(eSeverity severity) { *this = Severity(severity); }
      void setFrom(const Severity& severity) { *this = severity; }
      void setFrom(Severity&& severity) { *this = severity; }
  
      bool operator==(const Severity& severity) const noexcept { return (m_severity == severity.m_severity); }
      bool operator!=(const Severity& severity) const noexcept { return (m_severity != severity.m_severity); }
      bool operator<(const Severity& severity) const noexcept { return (m_severity < severity.m_severity); }
      bool operator<=(const Severity& severity) const noexcept { return (m_severity <= severity.m_severity); }
      bool operator>=(const Severity& severity) const noexcept { return (m_severity >= severity.m_severity); }
      bool operator>(const Severity& severity) const noexcept { return (m_severity > severity.m_severity); }
  
      std::string toString() const;
      static Severity fromString(const std::string& text);
      
      friend std::ostream& operator<<(std::ostream& output, const Severity& severity);
  
      friend Serialization::BinarySerializer& operator<<(Serialization::BinarySerializer& output, const Severity& severity)
      {
        output.storeValue(severity.m_severity);
        return output;
      }
      
      friend Serialization::BinaryDeserializer& operator>>(Serialization::BinaryDeserializer& input, Severity& severity)
      {
        input.readValue(severity.m_severity);
        return input;
      }
  
    private:
      eSeverity m_severity;
  
      static const char* m_severity_names[];
  
      static eSeverity convertTextToPossibleEnum(const std::string& text) noexcept;
  
      // vvv--- YOU CAN PUT ADDITIONAL CLASS ELEMENTS BELOW
  
      // ^^^--- END OF USER DEFINED CLASS ELEMENTS
  };
  
  constexpr Severity DATA { Severity(Severity::E_DATA) };
  constexpr Severity MEMO { Severity(Severity::E_MEMO) };
  constexpr Severity NOTICE { Severity(Severity::E_NOTICE) };
  constexpr Severity INFO { Severity(Severity::E_INFO) };
  constexpr Severity TRACE { Severity(Severity::E_TRACE) };
  constexpr Severity DEBUG { Severity(Severity::E_DEBUG) };
  constexpr Severity LOG { Severity(Severity::E_LOG) };
  constexpr Severity WARNING { Severity(Severity::E_WARNING) };
  constexpr Severity PROBLEM { Severity(Severity::E_PROBLEM) };
  constexpr Severity ERROR { Severity(Severity::E_ERROR) };
  constexpr Severity FATAL { Severity(Severity::E_FATAL) };
  constexpr Severity DISASTER { Severity(Severity::E_DISASTER) };
  constexpr Severity ARMAGEDON { Severity(Severity::E_ARMAGEDON) };

} // end Common
