// --------------------------------------------------------------------------------------
// File generated by metamorph meth code generator. File may be modified only inside 
// specially marked code blocks. Only such code can survive during subsequent generation 
// of the file. All other modification can be overwritten when generator is started.
// --------------------------------------------------------------------------------------
// This file is stored at:      .../development/test-of-generated-code/common_text_mesage.cpp
// and it is generated by:      .../test.py[111]
// based on pattern file:       .../patterns/string.cpp.body.pattern
// wrapped by pattern:          .../patterns/source.main.pattern
// (where '...' is solution root path)
// --------------------------------------------------------------------------------------

#include <sstream>

#include "common_text_mesage.h"
#include "common_conversion_error.h"

// -vvv YOU CAN PUT ADDITIONAL INCLUDES BELOW

// -^^^ END OF USER DEFINED INCLUDES

namespace Common
{
  
  // -vvv YOU CAN PUT ADDITIONAL DEFINITIONS BELOW
  
  // -^^^ END OF USER DEFINED DEFINITIONS

} // end Common
