// --------------------------------------------------------------------------------------
// File generated by metamorph meth code generator. File may be modified only inside 
// specially marked code blocks. Only such code can survive during subsequent generation 
// of the file. All other modification can be overwritten when generator is started.
// --------------------------------------------------------------------------------------
// This file is stored at:      .../development/test-of-generated-code/common_network_port_number.cpp
// and it is generated by:      .../test.py[82]
// based on pattern file:       .../patterns/integer.cpp.body.pattern
// wrapped by pattern:          .../patterns/common.main.pattern
// (where '...' is solution root path)
// --------------------------------------------------------------------------------------

#include <sstream>

#include "common_network_port_number.h"
#include "common_conversion_error.h"

// vvv--- YOU CAN PUT ADDITIONAL INCLUDES BELOW

// ^^^--- END OF USER DEFINED INCLUDES

namespace Common
{
  namespace Network
  {
    std::string PortNumber::toString() const
    {
      std::ostringstream string_representation;
      string_representation << *this;
      return string_representation.str();
    }
    
    PortNumber PortNumber::fromString(const std::string& text)
    {
      std::istringstream string_representation(text);
      uint16_t port_number = 0;
      string_representation >> port_number;
      if (!string_representation.eof())
      {
        throw Common::ConversionError(text, "cannot be interpreted as Common::Network::PortNumber");
      }
      return PortNumber(port_number);
    }
    
    std::ostream& operator<<(std::ostream& output, const PortNumber& port_number)
    {
      output << port_number.m_port_number;
      return output;
    }
    
    // vvv--- YOU CAN PUT ADDITIONAL CODE BELOW
    
    // ^^^--- END OF USER DEFINED CODE

  } // end Network
} // end Common
