// --------------------------------------------------------------------------------------
// This file is needed by the files generated by metamorph meth code generator. Initially
// it was copied from the patterns folder and can be used 'as it is', however you can 
// feel free to modify it or replace its content by whatever implementation you want. 
// Just keep interface used by the generated files. This file is created only when it does
// not exist. So when need to return to the default version - just remove it and run 
// generator once again.
// --------------------------------------------------------------------------------------
// This file is stored at: .../development/test-of-generated-code/common_size_error.h
// Copied from:            .../patterns/common_size_error.h.tool
// --------------------------------------------------------------------------------------

#pragma once

#include <string>

namespace Common
{
  class SizeError
  {
  public:
    SizeError(uint64_t p_requested_size, const std::string& problem)
      : requested_size(p_requested_size)
      , found_problem(problem)
    {  }

    uint64_t requested_size;
    const std::string found_problem;
  };
};
