// --------------------------------------------------------------------------------------
// This file is needed by the files generated by metamorph meth code generator. Initially
// it was copied from the patterns folder and can be used 'as it is', however you can 
// feel free to modify it or replace its content by whatever implementation you want. 
// Just keep interface used by the generated files. This file is created only when it does
// not exist. So when need to return to the default version - just remove it and run 
// generator once again.
// --------------------------------------------------------------------------------------
// This file is stored at: .../development/test-of-generated-code/common_text_converter.h
// Copied from:            .../patterns/common_text_converter.h.tool
// --------------------------------------------------------------------------------------

#pragma once

#include <string>

namespace Common
{
  class TextConverter
  {
    public:
      static void ensureStaticTextExist(std::string::const_iterator & reader, std::string::const_iterator & limit, const char* pattern);
      static int readOneOrTwoDigitsNumber(std::string::const_iterator& reader, std::string::const_iterator& limit);
      static int readTwoDigitsNumber(std::string::const_iterator& reader, std::string::const_iterator& limit);
      static int readThreeDigitsNumber(std::string::const_iterator& reader, std::string::const_iterator& limit);
      static int readFourDigitsNumber(std::string::const_iterator& reader, std::string::const_iterator& limit);
      static int readNumber(std::string::const_iterator& reader, std::string::const_iterator& limit);
  };

}
