// --------------------------------------------------------------------------------------
// File generated by metamorph meth code generator. File may be modified only inside 
// specially marked code blocks. Only such code can survive during subsequent generation 
// of the file. All other modification can be overwritten when generator is started.
// --------------------------------------------------------------------------------------
// This file is stored at:      .../development/test-of-generated-code/configuration_nodes.cpp
// and it is generated by:      .../test.py[148]
// based on pattern file:       .../patterns/collection.cpp.body.pattern
// wrapped by pattern:          .../patterns/common.main.pattern
// (where '...' is solution root path)
// --------------------------------------------------------------------------------------

#include <sstream>

#include "configuration_nodes.h"
#include "common_conversion_error.h"
#include "configuration_node.h"

// -vvv YOU CAN PUT ADDITIONAL INCLUDES BELOW

// -^^^ END OF USER DEFINED INCLUDES

namespace Configuration
{
  std::string Nodes::toString() const
  {
    std::ostringstream string_representation;
    string_representation << *this;
    return string_representation.str();
  }
  
  std::ostream& operator<<(std::ostream& output, const Nodes& nodes)
  {
    
    
    
    return output;
  }
  
  Serialization::BinarySerializer& operator<<(Serialization::BinarySerializer& serializer, const Nodes& nodes)
  {
    
    
    
    return serializer;
  }
  
  Serialization::BinaryDeserializer& operator>>(Serialization::BinaryDeserializer& deserializer, Nodes& nodes)
  {
    
    
    
    return deserializer;
  }
  
  // -vvv YOU CAN PUT ADDITIONAL CODE BELOW
  
  // -^^^ END OF USER DEFINED CODE

} // end Configuration
