// --------------------------------------------------------------------------------------
// File generated by metamorph meth code generator. File may be modified only inside 
// specially marked code blocks. Only such code can survive during subsequent generation 
// of the file. All other modification can be overwritten when generator is started.
// --------------------------------------------------------------------------------------
// This file is stored at:      .../development/test-of-generated-code/configuration_nodes.h
// and it is generated by:      .../test.py[149]
// based on pattern file:       .../patterns/collection.h.body.pattern
// wrapped by pattern:          .../patterns/common.main.pattern
// (where '...' is solution root path)
// --------------------------------------------------------------------------------------

#pragma once

#include <vector>
#include <string>
#include <iostream>

#include "common_size_error.h"
#include "serialization_binary_serialization.h"

namespace Configuration
{
  class Node;
}

// vvv--- YOU CAN PUT ADDITIONAL INCLUDES BELOW

// ^^^--- END OF USER DEFINED INCLUDES

namespace Configuration
{
  class Nodes
  {
    public:
      // type traits
      static constexpr const char* class_name = { "Configuration::Nodes" };
      static constexpr bool is_compareable = { true };
      static constexpr bool is_ordered = { true };
      static constexpr uint16_t max_count = { 64000 };
  
      Nodes() = default;
      Nodes(const Nodes& nodes) = default;
      Nodes(Nodes&& nodes) = default;
      Nodes& operator=(const Nodes& nodes) = default;
      Nodes& operator=(Nodes&& nodes) = default;
  
      void insertNode(const Node& node) { m_nodes.push_back(node); checkSize(); }
      void insertNode(Node&& node) { m_nodes.push_back(node); checkSize(); }
  
      uint16_t getNodesCount() const { return static_cast<uint16_t>(m_nodes.size()); }
  
      bool operator==(const Nodes& nodes) const noexcept;
      bool operator!=(const Nodes& nodes) const noexcept;
      bool operator<(const Nodes& nodes) const noexcept;
      bool operator<=(const Nodes& nodes) const noexcept;
      bool operator>=(const Nodes& nodes) const noexcept;
      bool operator>(const Nodes& nodes) const noexcept;
  
      // ...
  
      std::string toString() const;
  
      friend std::ostream& operator<<(std::ostream& output, const Nodes& nodes);
  
      friend Serialization::BinarySerializer& operator<<(Serialization::BinarySerializer& output, const Nodes& nodes);
      friend Serialization::BinaryDeserializer& operator>>(Serialization::BinaryDeserializer& input, Nodes& nodes);
  
    private:
      std::vector<Configuration::Node> m_nodes;
  
      void checkSize()
      {
        // vvv--- YOU CAN PUT VALUE CHECK HANDLING HERE
        if (getNodesCount() > max_count)
        {
          throw Common::SizeError(getNodesCount(), "too long string to initiate Nodes");
        }
        // ^^^--- END OF VALUE CHECK HANDLING HERE
      }
  
      // vvv--- YOU CAN PUT ADDITIONAL CLASS ELEMENTS BELOW
  
      // ^^^--- END OF USER DEFINED CLASS ELEMENTS
  };
} // end Configuration
