// --------------------------------------------------------------------------------------
// File generated by metamorph meth code generator. File may be modified only inside 
// specially marked code blocks. Only such code can survive during subsequent generation 
// of the file. All other modification can be overwritten when generator is started.
// --------------------------------------------------------------------------------------
// This file is stored at:      .../development/test-of-generated-code/money_netto.h
// and it is generated by:      .../test.py[119]
// based on pattern file:       .../patterns/float.h.body.pattern
// wrapped by pattern:          .../patterns/source.main.pattern
// (where '...' is solution root path)
// --------------------------------------------------------------------------------------

#pragma once

#include <cstdint>
#include <string>
#include <iostream>

#include "serialization_binary_serialization.h"

// -vvv YOU CAN PUT ADDITIONAL INCLUDES BELOW

// -^^^ END OF USER DEFINED INCLUDES

namespace Money
{
  class Netto
  {
    public:
      // type traits
      static constexpr const char* class_name = { "Money::Netto" };
      static constexpr bool is_compareable = { true };
      static constexpr bool is_ordered = { true };
      static constexpr float accuracy = { 0.005 };
  
      constexpr Netto() noexcept
        : m_netto(0.0)
      {  }
  
      constexpr explicit Netto( float netto ) noexcept
        : m_netto(netto)
      {  }
  
      Netto(const Netto& netto) noexcept = default;
      Netto(Netto&& netto) noexcept = default;
      Netto& operator=(const Netto& netto) noexcept = default;
      Netto& operator=(Netto&& netto) noexcept = default;
  
  
  
  
  
  
  
    private:
      float m_netto;
  
      // -vvv YOU CAN PUT ADDITIONAL CLASS ELEMENTS BELOW
  
      // -^^^ END OF USER DEFINED CLASS ELEMENTS
  };
} // end Money
