// --------------------------------------------------------------------------------------
// File generated by metamorph meth code generator. File may be modified only inside 
// specially marked code blocks. Only such code can survive during subsequent generation 
// of the file. All other modification can be overwritten when generator is started.
// --------------------------------------------------------------------------------------
// This file is stored at:      .../development/test-of-generated-code/money_netto.cpp
// and it is generated by:      .../test.py[122]
// based on pattern file:       .../patterns/float.cpp.body.pattern
// wrapped by pattern:          .../patterns/source.main.pattern
// (where '...' is solution root path)
// --------------------------------------------------------------------------------------

#include <sstream>

#include "money_netto.h"
#include "common_conversion_error.h"

// -vvv YOU CAN PUT ADDITIONAL INCLUDES BELOW

// -^^^ END OF USER DEFINED INCLUDES

namespace Money
{
  Netto Netto::fromString(const std::string& text)
  {
    std::istringstream string_representation(text);
    float netto = 0;
    string_representation >> netto;
    if (!string_representation.eof())
    {
      throw Common::ConversionError(text, "cannot be interpreted as Money::Netto");
    }
    return Netto(netto);
  }
  
  // -vvv YOU CAN PUT ADDITIONAL DEFINITIONS BELOW
  
  // -^^^ END OF USER DEFINED DEFINITIONS

} // end Money
