// --------------------------------------------------------------------------------------
// File generated by metamorph meth code generator. File may be modified only inside 
// specially marked code blocks. Only such code can survive during subsequent generation 
// of the file. All other modification can be overwritten when generator is started.
// --------------------------------------------------------------------------------------
// This file is stored at:      .../development/test-of-generated-code/test_the_door.cpp
// and it is generated by:      .../test.py[102]
// based on pattern file:       .../patterns/state.machine.cpp.body.pattern
// wrapped by pattern:          .../patterns/common.main.pattern
// (where '...' is solution root path)
// --------------------------------------------------------------------------------------

#include "test_the_door.h"

// vvv--- YOU CAN PUT ADDITIONAL INCLUDES BELOW

// ^^^--- END OF USER DEFINED INCLUDES

namespace Test
{
  void TheDoor::Closed::process_event(Event event, TheDoor& the_door)
  {
    
  }
  
  void TheDoor::Opened::process_event(Event event, TheDoor& the_door)
  {
    
  }
  
  void TheDoor::Locked::process_event(Event event, TheDoor& the_door)
  {
    
  }
  
  // vvv--- TheDoor additional fields and methods
  
  // ^^^--- End of TheDoor additional fields and methods

} // end Test
