// --------------------------------------------------------------------------------------
// File generated by metamorph meth code generator. File may be modified only inside 
// specially marked code blocks. Only such code can survive during subsequent generation 
// of the file. All other modification can be overwritten when generator is started.
// --------------------------------------------------------------------------------------
// This file is stored at:      .../development/test-of-generated-code/test_another_record.h
// and it is generated by:      .../test.py[140]
// based on pattern file:       .../patterns/record.h.body.pattern
// wrapped by pattern:          .../patterns/common.main.pattern
// (where '...' is solution root path)
// --------------------------------------------------------------------------------------

#pragma once

#include <string>
#include <iostream>

#include "common_severity.h"
#include "common_network_port_number.h"
#include "serialization_binary_serialization.h"

// vvv--- YOU CAN PUT ADDITIONAL INCLUDES BELOW

// ^^^--- END OF USER DEFINED INCLUDES

namespace Test
{
  class AnotherRecord 
    : public Common::Severity
    , public Common::Network::PortNumber
  {
    public:
      // type traits
      static constexpr const char* class_name = { "Test::AnotherRecord" };
      static constexpr bool is_compareable = { false };
      static constexpr bool is_ordered = { false };
  
      typedef std::unique_ptr<AnotherRecord> Owner;
  
      AnotherRecord() = default;
  
      AnotherRecord(const AnotherRecord& another_record) noexcept
      : Common::Severity(another_record)
      , Common::Network::PortNumber(another_record)
      {  }
  
      AnotherRecord(AnotherRecord&& another_record) noexcept
      : Common::Severity(another_record)
      , Common::Network::PortNumber(another_record)
      {  }
  
      AnotherRecord(const Common::Severity& common_severity,
                    const Common::Network::PortNumber& common_network_port_number) noexcept
      : Common::Severity(common_severity)
      , Common::Network::PortNumber(common_network_port_number)
      {  }
  
      AnotherRecord(Common::Severity&& common_severity,
                    Common::Network::PortNumber&& common_network_port_number) noexcept
      : Common::Severity(common_severity)
      , Common::Network::PortNumber(common_network_port_number)
      {  }
  
      AnotherRecord& operator=(const AnotherRecord& another_record) noexcept = default;
      AnotherRecord& operator=(AnotherRecord&& another_record) noexcept = default;
  
      template <class OTHER>
      void setFrom(const OTHER& other)
      {
        if constexpr(std::is_base_of_v<Common::Severity, OTHER>)
        {
          Common::Severity::setFrom(other);
        }
        else if constexpr(std::is_base_of_v<OTHER, Common::Severity>)
        {
          Common::Severity::setFrom(other);
        }
        if constexpr(std::is_base_of_v<Common::Network::PortNumber, OTHER>)
        {
          Common::Network::PortNumber::setFrom(other);
        }
        else if constexpr(std::is_base_of_v<OTHER, Common::Network::PortNumber>)
        {
          Common::Network::PortNumber::setFrom(other);
        }
      }
  
      template <class OTHER>
      void setFrom(OTHER&& other)
      {
        if constexpr(std::is_base_of_v<typename std::remove_reference<OTHER>::type, Common::Severity>)
        {
          Common::Severity::setFrom(other);
        }
        else if constexpr(std::is_base_of_v<Common::Severity, typename std::remove_reference<OTHER>::type>)
        {
          Common::Severity::setFrom(other);
        }
        if constexpr(std::is_base_of_v<typename std::remove_reference<OTHER>::type, Common::Network::PortNumber>)
        {
          Common::Network::PortNumber::setFrom(other);
        }
        else if constexpr(std::is_base_of_v<Common::Network::PortNumber, typename std::remove_reference<OTHER>::type>)
        {
          Common::Network::PortNumber::setFrom(other);
        }
      }
  
      // No compare operators
      // No ordering operators
  
      std::string toString() const;
  
      friend std::ostream& operator<<(std::ostream& output, const AnotherRecord& another_record);
  
      friend Serialization::BinarySerializer& operator<<(Serialization::BinarySerializer& output, const AnotherRecord& another_record);
      friend Serialization::BinaryDeserializer& operator>>(Serialization::BinaryDeserializer& input, AnotherRecord& another_record);
  
      // vvv--- YOU CAN PUT ADDITIONAL CLASS ELEMENTS BELOW
  
      // ^^^--- END OF USER DEFINED CLASS ELEMENTS
  };
} // end Test
